#!/bin/bash
# converts a boolector model to queens format that can be read by queensgui
declare -a positions

read line
if [[ $line != sat ]]; then
  echo "invalid format"
  exit 1
fi
numqueens=0
while read line
do
  queen=`echo $line | awk '{print $2}'`
  if [[ $queen -eq 1 ]]; then
    boardstring=`echo $line | awk '{print $1}'`
    posstring=${boardstring:5}
    positions[$numqueens]=$posstring
    ((numqueens++))
  fi
done
if [[ $numqueens -le 0 ]]; then
  echo "invalid format"
  exit 1
fi
echo $numqueens
for ((i = 0; i < $numqueens; i++))
do
  posstring=${positions[$i]}
  x=`echo $posstring | awk -F_ '{print $1}'`
  y=`echo $posstring | awk -F_ '{print $2}'`
  echo "$x $y"
done

