#!/usr/bin/env python
import sys, getopt

REGULAR_MODE = 0
PIGEON_HOLE_MODE_NP1 = 1
PIGEON_HOLE_MODE_GTN = 2

def usage():
  print "usage: nqueens [-h] [-s <size>] [-p <mode>]"
  sys.exit(0)

def die(msg):
  assert msg != None
  print msg
  sys.exit(1)

def is_power_of_2 (x):
  assert x > 0
  return (x & (x - 1)) == 0

def next_power_of_2 (x):
  assert x > 0
  x -= 1
  i = 1
  while i < 32:
    x = x | (x >> i)
    i *= 2
  return x + 1

def log2 (x):
  result = 0
  assert x > 0
  assert is_power_of_2 (x)
  while x > 1:
    x >>= 1
    result += 1
  assert result >= 0
  return result

def board_field (x, y):
  assert x >= 0
  assert y >= 0
  return "board" + str(x) + "_" + str(y)

mode = REGULAR_MODE
size = 8
id = 1
constraints = [] 

try:
  opts, args = getopt.getopt(sys.argv[1:], "hp:s:")
except getopt.GetoptError, err:
  print str(err)
  usage()

for o, a in opts:
  if o in ("-h"):
    usage()
  elif o in ("-p"):
    if a == "1":
      mode = PIGEON_HOLE_MODE_NP1
    elif a == "2":
      mode = PIGEON_HOLE_MODE_GTN
    else:
      die ("mode must be 1 or 2")
  elif o in ("-s"):
    size = int (a)
    if size < 4:
      die ("size must be >= 4")

num_bits_size = log2 (next_power_of_2 (size + 1))

print "(benchmark nqueens" + str(size) + "x" + str(size)
print ":source {"
print "Bit-vector encoding of n-queens problem with " + str(size) + " queens"
if mode == PIGEON_HOLE_MODE_NP1: 
  print "We try to place n + 1 queens on an n x n board"
elif mode == PIGEON_HOLE_MODE_GTN:
  print "We try to place m queens on an n x n board with m > n"
print "Contributed by Robert Brummayer (robert.brummayer@gmail.com)"
print "}"
if mode == REGULAR_MODE:
  print ":status sat"
else:
  print ":status unsat"
print ":logic QF_BV"
for i in range(size):
  for j in range(size):
    print ":extrafuns ((" + board_field(i, j) + " BitVec[1]))"
print ":formula"

# generate row constraints 
for i in range(size):
  print "(let (?e" + str(id) + " (zero_extend[" + str(num_bits_size - 1) + \
        "] " + board_field(i, 0) + "))"
  last = "?e" + str(id)
  id += 1
  for j in range(1, size):
    print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
          str(num_bits_size - 1) + "] " + board_field(i, j) + ")))"
    last = "?e" + str(id)
    id += 1
  print "(flet ($e" + str(id) + " (= " + last + " bv1[" + \
        str(num_bits_size) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

# generate col constraints 
for i in range(size):
  print "(let (?e" + str(id) + " (zero_extend[" + str(num_bits_size - 1) + \
        "] " + board_field(0, i) + "))"
  last = "?e" + str(id)
  id += 1
  for j in range(1, size):
    print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
          str(num_bits_size - 1) + "] " + board_field(j, i) + ")))"
    last = "?e" + str(id)
    id += 1
  print "(flet ($e" + str(id) + " (= " + last + " bv1[" + \
        str(num_bits_size) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

#generate diagonal constraints
for i in range(1, size):
  print "(let (?e" + str(id) + " (zero_extend[" + str(num_bits_size - 1) + \
        "] " + board_field(i, 0) + "))"
  last = "?e" + str(id)
  id += 1
  row = i - 1
  col = 1
  assert row >= 0 and col < size 
  while row >= 0 and col < size:
    print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
          str(num_bits_size - 1) + "] " + board_field(row, col) + ")))"
    last = "?e" + str(id)
    id += 1
    row -= 1
    col += 1
  print "(flet ($e" + str(id) + " (bvule " + last + " bv1[" + \
        str(num_bits_size) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

for i in range(1, size - 1):
  print "(let (?e" + str(id) + " (zero_extend[" + str(num_bits_size - 1) + \
        "] " + board_field(size - 1, i) + "))"
  last = "?e" + str(id)
  id += 1
  row = size - 1 - 1
  col = i + 1
  assert row >= 0 and col < size 
  while row >= 0 and col < size: 
    print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
          str(num_bits_size - 1) + "] " + board_field(row, col) + ")))"
    last = "?e" + str(id)
    id += 1
    row -= 1
    col += 1
  print "(flet ($e" + str(id) + " (bvule " + last + " bv1[" + \
        str(num_bits_size) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

for i in range(1, size):
  print "(let (?e" + str(id) + " (zero_extend[" + str(num_bits_size - 1) + \
        "] " + board_field(i, size - 1) + "))"
  last = "?e" + str(id)
  id += 1
  row = i - 1
  col = size - 1 - 1
  assert row >= 0 and col >= 0 
  while row >= 0 and col >= 0:
    print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
          str(num_bits_size - 1) + "] " + board_field(row, col) + ")))"
    last = "?e" + str(id)
    id += 1
    row -= 1
    col -= 1
  print "(flet ($e" + str(id) + " (bvule " + last + " bv1[" + \
        str(num_bits_size) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

for i in range(1, size - 1):
  print "(let (?e" + str(id) + " (zero_extend[" + str(num_bits_size - 1) + \
        "] " + board_field(size - 1, size - 1 - i) + "))"
  last = "?e" + str(id)
  id += 1
  row = size - 1 - 1
  col = size - 1 - i - 1 
  assert row >= 0 and col >= 0 
  while row >= 0 and col >= 0: 
    print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
          str(num_bits_size - 1) + "] " + board_field(row, col) + ")))"
    last = "?e" + str(id)
    id += 1
    row -= 1
    col -= 1
  print "(flet ($e" + str(id) + " (bvule " + last + " bv1[" + \
        str(num_bits_size) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

# generate pigeon hole constraint
if mode == PIGEON_HOLE_MODE_NP1 or mode == PIGEON_HOLE_MODE_GTN:
  fields = size * size;
  num_bits_fields = log2 (next_power_of_2 (fields + 1))
  print "(let (?e" + str(id) + " bv0[" + str(num_bits_fields) + "])"
  last = "?e" + str(id)
  id += 1
  for i in range(size):
    for j in range(size):
      print "(let (?e" + str(id) + " (bvadd " + last + " " + "(zero_extend[" + \
            str(num_bits_fields - 1) + "] " + board_field(i, j) + ")))"
      last = "?e" + str(id)
      id += 1
  if mode == PIGEON_HOLE_MODE_NP1:
    print "(flet ($e" + str(id) + " (= " + last + " bv" + str(size + 1) + \
           "[" + str(num_bits_fields) + "]))"
  else:
    assert mode == PIGEON_HOLE_MODE_GTN
    print "(flet ($e" + str(id) + " (bvugt " + last + " bv" + str(size) + \
           "[" + str(num_bits_fields) + "]))"
  constraints.append ("$e" + str(id))
  id += 1

# combine all constraints by AND
assert len(constraints) >= 2
last = constraints[0]
for i in range(1, len(constraints)):
  print "(flet ($e" + str(id) + " (and " + last + " " + constraints[i] + "))" 
  last = "$e" + str(id)
  id += 1
print last
pars = ""
for i in range(id):
  pars = pars + ")"
print pars
