#!/bin/bash
# converts a z3 2.0 model to queens format that can be read by queensgui
declare -a positions

numqueens=0
while read line
do
  line=`echo $line | tr -d '\r'`
  if [[ $line != sat ]]; then
    queen=`echo $line | awk '{print $3}'`
    if [[ $queen == 1 ]] || [[ $queen == 'bv1[1]' ]]; then
      boardstring=`echo $line | awk '{print $1}'`
      posstring=${boardstring:5}
      positions[$numqueens]=$posstring
      ((numqueens++))
    fi
  fi
done
if [[ $numqueens -le 0 ]]; then
  echo "invalid format"
  exit 1
fi
echo $numqueens
for ((i = 0; i < $numqueens; i++))
do
  posstring=${positions[$i]}
  x=`echo $posstring | awk -F_ '{print $1}'`
  y=`echo $posstring | awk -F_ '{print $2}'`
  echo "$x $y"
done

