#!/bin/bash

filebasic="/tmp/addmincovtestsbasic$$.tmp"
fileformula="/tmp/addmincovtestsformula$$.tmp"
fileboolector="/tmp/addmincovtestsboolector$$.tmp"
filereduced="/tmp/addmincovtestsreduced$$.tmp"
covdir="covtests/"

deltabtor=unknown
for d in `echo $PATH | sed -e 's,:, ,g'` .
do
  file=$d/deltabtor
  [ -d $d ] || continue
  [ -f $file ] || continue
  deltabtor=$file
  break
done
if [[ $deltabtor = unknown ]]; then
  echo "*** addmincovtests: can not find 'deltabtor'" 1>&2
  exit 1
fi

if [[ ! -e $covdir ]] || [[ ! -d $covdir ]] || [[ ! -r $covdir ]]; then
  echo "*** addmincovtests: can not read coverage test directory" 1>&2
  exit 1
fi
  
./gencovformula > $fileformula

if [[ $? -ne 0 ]]; then
  echo "Formula could not be generated"
  exit 1
fi

rm -f $filebasic

#compute test id
maxline=`grep covtest ~/boolector/testcases | sort | tail -n 1`
if [[ -n "$maxline" ]]; then
  maxcol=`echo "$maxline" | awk '{ print $1 }'`
  testid=${maxcol##covtest}
  ((testid++))
else
  testid=1
fi

exec 10<"$fileformula"
while read line <&10
do
  op=`echo "$line" | awk '{ print $2 }'`
  if [[ "$op" = ulte ]]; then
    id=`echo "$line" | awk '{ print $1 }'`
    idsum=`echo "$line" | awk '{ print $4 }'`
    break
  else
    echo "$line" >> $filebasic
  fi
done
# close file
exec 10>&-

echo "found "`ls "$covdir"*.btor | wc -l`" tests"
echo "computing minimal number of tests" >&2
num=1
result=unsat
while [[ "$result" = unsat ]]
do
  echo "Trying number of tests = $num" >&2
  cp $filebasic $fileformula
  echo "$id constd 32 $num" >> $fileformula
  echo "$((id + 1)) eq 1 $idsum $id" >> $fileformula
  echo "$((id + 2)) root 1 $((id + 1))" >> $fileformula
  boolector $fileformula -m 1> $fileboolector 2> /dev/null
  result=`head -n 1 $fileboolector`
  if [[ "$result" = sat ]]; then
    exec 10<"$fileboolector"
    skipfirstline=1
    while read line <&10
    do
      if [[ $skipfirstline -eq 1 ]]; then
        skipfirstline=0
      else
        if [[ `echo "$line" | awk '{ print $2 }'` -eq 1 ]]; then
	  testbase=`echo "$line" | awk '{ print $1 }'`
	  errfile="$covdir""$testbase"".err"
	  csfile="$covdir""$testbase"".cs"
	  cp "$errfile" "$covdir""fileerr"
	  cp "$csfile" "$covdir""filecs"
	  echo "minimizing $testbase" >&2
	  testfile="$covdir""$testbase"".btor"
	  $deltabtor "$testfile" $filereduced ./covdeltadebrun
	  cp $filereduced ~/boolector/log/covtest$testid".btor"
	  boolector -rwl0 "$filereduced" \
	  1> ~/boolector/log/covtest$testid".out" 2> /dev/null
	  testcasesline=covtest$testid" "`cat "$csfile"`" -o log/covtest$testid"".log log/covtest$testid"".btor"
	  echo "$testcasesline" >> ~/boolector/testcases
	  ((testid++))
	fi
      fi
    done
    # close file
    exec 10>&-
  else
    ((num++))
  fi
done

echo "added $num tests" >&2
cd ~/boolector/log
git add -f covtest*.*
