#!/bin/bash
readonly usage='btor2aig [--no-rewriting]'

if [[ $# -ne 0 ]] && [[ $# -ne 1 ]]; then
  echo $usage
  exit 1
fi

if [[ $# -eq 1 ]]; then
  if [[ $1 != "--no-rewriting" ]]; then 
    echo $usage
    exit 1
  fi
  rw='-rwl 0'
fi

boolector=`which boolector`
if [[ -z "$boolector" ]]; then
  echo "can not find 'boolector'" 1>&2
  exit 1
fi

synthebtor=`which synthebtor`
if [[ -z "$synthebtor" ]]; then
  echo "can not find 'synthebtor'" 1>&2
  exit 1
fi

aigtoaig=`which aigtoaig`
if [[ -z "$aigtoaig" ]]; then
  echo "can not find 'aigtoaig'" 1>&2
  exit 1
fi

cont=""
#check if btor file does not have arrays
while read line
do
  keyword=`echo $line | awk '{print $2}'`
  if [[ "$keyword" == "array" ]]; then
    echo "arrays are not supported" 1>&2
    exit 1
  fi
  cont="$cont${line}\n"
done

echo -e $cont | $boolector $rw -db | $synthebtor -m | $aigtoaig
