#!/usr/bin/awk -f
{ 

  if ($2 == "array") {
    power[$1] = $4
    print $0
  } else if ($2 == "cond") {
    if ($5 in power)
    {
      if (! ($6 in power)) {
        printf "Second parameter must also be an array\n"
        exit 1
      }
      printf "%d acond %d %d %d %d %d\n", $1, $3, power[$5], $4, $5, $6, $7
      power[$1] = power[$5] 
    } else {
      print $0
    }
  } else if ($2 == "write") {
    power[$1] = power[$4] 
    printf "%d write %d %d %d %d %d\n", $1, $3, power[$4], $4, $5, $6, $7
  } else {
    print $0
  } 

}

