#!/bin/sh
if [ $# -gt 1 ]; then
  echo "Usage: ./btorvis.sh <filename>"
  exit 1
fi
temp=/tmp/btorvis$$
pstemp=$temp".ps"
pdftemp=$temp".pdf"
btor2dot=unknown
for d in `echo $PATH|sed -e 's,:, ,g'` .
do
  file=$d/btor2dot
  [ -d $d ] || continue
  [ -f $file ] || continue
  btor2dot=$file
  break
done
if [ $btor2dot = unknown ]
then
  echo "*** btorvis: can not find 'btor2dot'" 1>&2
  exit 1
fi
cat $*|$btor2dot | dot -Tps2 > $pstemp
ps2pdf $pstemp $pdftemp || exit 1
evince $pdftemp
rm -f $pstemp $pdftemp
