#!/bin/bash

author=$1
year=$2
since="$year-01-01"
until="$((year+1))-01-01"

[ "$author" == "" -o "$year" == "" ] && \
  echo "error: no author and year given" && \
  echo "usage: $(basename $0) <author> <yyyy>" && \
  exit 1 

for f in $(./contrib/git-show-changed-files "$author" "$since" "$until"); do
  if [ ! -e $f ]; then
    continue
  fi

  echo -n "$f: "
  echo "$(head -n 20 $f | grep -i copyright | grep -i $author)"
done
