#!/bin/bash

readonly filebasic="/tmp/computemincovtestsbasic$$.tmp"
readonly fileformula="/tmp/computemincovtestsformula$$.tmp"
readonly fileboolector="/tmp/computemincovtestsboolector$$.tmp"
readonly covdir="covtests/"
readonly usage="./computemincovtests [-a]"
readonly cores=4
readonly selected="${covdir}selected"

function cleanup
{
  killall minimizecovtests &> /dev/null
  rm -f "$fileformula"
  rm -f "$fileboolector"
  rm -f "$selected"
}

trap 'cleanup; exit 0' SIGHUP SIGINT SIGTERM

deltabtor=unknown
for d in `echo $PATH | sed -e 's,:, ,g'` .
do
  file=$d/deltabtor
  [ -d $d ] || continue
  [ -f $file ] || continue
  deltabtor=$file
  break
done
if [[ "$deltabtor" = unknown ]]; then
  echo "*** computemincovtests: can not find 'deltabtor'" 1>&2
  exit 1
fi

if [[ ! -e "$covdir" ]] || [[ ! -d "$covdir" ]] || [[ ! -r "$covdir" ]]; then
  echo "*** computemincovtests: can not read coverage test directory" 1>&2
  exit 1
fi

add=0
while getopts "a" o
do
  case "$o" in
  a)	add=1;;
  [?])	echo "$usage" 1>&2; exit 1;;
  esac
done
  
./gencovformula > "$fileformula"

if [[ $? -ne 0 ]]; then
  echo "Formula could not be generated"
  exit 1
fi

rm -f "$filebasic"

while read line
do
  op=`echo "$line" | awk '{ print $2 }'`
  if [[ "$op" = ulte ]]; then
    id=`echo "$line" | awk '{ print $1 }'`
    idsum=`echo "$line" | awk '{ print $4 }'`
    break
  else
    echo "$line" >> $filebasic
  fi
done < "$fileformula"

rm -f "$selected"

echo "found "`ls "$covdir"*.btor | wc -l`" tests"
echo "computing minimal number of tests" >&2
num=1
result=unsat
while [[ "$result" = unsat ]]
do
  echo "trying number of tests = $num" >&2
  cp $filebasic $fileformula
  echo "$id constd 32 $num" >> $fileformula
  echo "$((id + 1)) eq 1 $idsum $id" >> $fileformula
  echo "$((id + 2)) root 1 $((id + 1))" >> $fileformula
  boolector $fileformula -m 1> $fileboolector 2> /dev/null
  result=`head -n 1 $fileboolector`
  if [[ "$result" = sat ]]; then
    skipfirstline=1
    while read line
    do
      if [[ "$skipfirstline" -eq 1 ]]; then
        skipfirstline=0
      else
        if [[ `echo "$line" | awk '{ print $2 }'` -eq 1 ]]; then
	  echo "$line" | awk '{ print $1 }' >> "$selected"
	fi
      fi
    done < "$fileboolector"
  else
    ((num++))
  fi
done

for ((i = 1; i <= "$cores"; i++))
do
  ./minimizecovtests -i "$i" &
  sleep 1
done

minimized=0
while [[ "$minimized" -lt "$num" ]]
do
  minimized=`ls ${covdir}*.red 2> /dev/null | wc -l`
  echo "$minimized"
  sleep 1
done


if [[ "$add" -eq 1 ]]; then
  #compute test id
  maxline=`grep covtest ~/boolector/testcases | sort | tail -n 1`
  if [[ -n "$maxline" ]]; then
    maxcol=`echo "$maxline" | awk '{ print $1 }'`
    testid=${maxcol##covtest}
    ((testid++))
  else
    testid=1
  fi

  while read line
  do
    reducedfile="$covdir${line}.red"
    csfile="$covdir${line}.cs"
    cp $reducedfile ~/boolector/log/covtest$testid".btor"
    boolector -rwl0 "$reducedfile" \
    1> ~/boolector/log/covtest$testid".out" 2> /dev/null
    testcasesline=covtest$testid" "`cat "$csfile"`" -o log/covtest$testid"".log log/covtest$testid"".btor"
    echo "$testcasesline" >> ~/boolector/testcases
    ((testid++))
  done < "$selected"
  echo "added $num tests" >&2
  cd ~/boolector/log
  git add -f covtest*.*
else
  echo "minimized $num tests" >&2
fi
cleanup
