#!/bin/bash
temp="/tmp/covdeltadebrun$$.tmp"
output="/tmp/covdeltadebrun$$output.tmp"

covdir="covtests/"
cs=`cat "$covdir""filecs"`

boolector $cs $1 1> /dev/null 2> $output
cat "$output" | sort | uniq > $temp
diff -q "$temp" "$covdir""fileerr"
if [[ -z `diff -q "$temp" "$covdir""fileerr"` ]]; then
  exit 1
fi

exit 0

