#! /bin/sh

ddtesttmpfile="/tmp/ddtesttmp-$$.out"
ddreftmpfile="/tmp/ddreftmp-$$.out"

die () 
{
  echo "*** ddout: $*" 1>&2
  exit 1
}

cleanup ()
{
  rm -f $ddtesttmpfile > /dev/null 2>&1
  rm -f $ddreftmpfile > /dev/null 2>&1
}

trap "cleanup;exit 2" SIGHUP SIGINT SIGTERM

ddcmd=""
ddcmdopts=""
ddrefinfile=""
ddtestinfile=""

while [ $# -gt 0 ]
do
  case $1 in
    -h|--help)
      echo -n "usage: $(basename $0) [<option>] <cmd> [<cmdopts>] "
      echo "<reffile> <testfile>"
      echo
      echo "  <test>:     the solver instance under test"
      echo "  <testopts>: options passed to <test>"
      echo "  <reffile>:  the reference input file"
      echo "  <testfile>: the test input file"
      echo
      echo "  options:"
      echo "    -h, --help    print this message and exit"
      echo
      exit
      ;;
    -*|[0-9]*) 
      if [ x"$ddtest" = x ]; then
	die "invalid option: $1"
      elif [ x"$ddref" = x  ]; then
	ddtestopts="$ddtestopts $1"
      fi
      ;;
    *) 
      if [ x"$ddcmd" = x ]; then
	ddcmd=$1
      elif [ x"$ddrefinfile" = x  ]; then
	ddrefinfile=$1
      elif [ x"$ddtestinfile" = x  ]; then 
	ddtestinfile=$1
      else
	break
      fi
      ;;
  esac
  shift
done

[ x"$ddrefinfile" = x ] && die "reference input file missing"
[ x"$ddtestinfile" = x ] && die "test input file missing"
[ x"$ddcmd" = x ] && die "executable missing"

$ddcmd $ddcmdopts $ddrefinfile 2> $ddreftmpfile > /dev/null
refresult=$?
$ddcmd $ddcmdopts $ddtestinfile 2> $ddtesttmpfile > /dev/null
testresult=$?

if [ $testresult -eq $refresult ]; then
  cmp $ddreftmpfile $ddtesttmpfile > /dev/null 2>&1
  res=$?
  if [ $res -eq 0 ]; then
    rm $ddtesttmpfile $ddreftmpfile
    exit 1
  fi
fi
rm $ddtesttmpfile $ddreftmpfile
exit 0
