#!/bin/bash

readonly DELTABTOR=./deltabtor
readonly ERRORLOG=/tmp/ddassert_error_$$.log
contribdir=$(dirname $(readlink -f $0))
readonly DDASSERT=$(readlink -f "$contribdir/ddassert")

die () {
  echo "*** $(basename $0): $*" 1>&2
  exit 1
}

trap "exit" SIGHUP SIGINT SIGTERM

in=""
out=""
cmd=""

while [ $# -gt 0 ]
do
  case $1 in
    -h|--help) 
               echo -n "usage: $(basename $0) "
               echo "[<option>] <infile> <outfile> \"<command>\""
               echo
               echo "  <infile>:          the input file"
	       echo "  <outfile>:         the (reduced) output file"
               echo
               echo "  options:"
               echo "    -h,--help        print this message and exit"
               echo
               exit
               ;;
    *) if [ x"$in" = x ]; then
         in="$1"
       elif [ x"$out" = x ]; then
         out="$1"
       elif [ x"$cmd" = x ]; then
         cmd="\"$1\""
       else
         die "invalid number of arguments, try --help (-h)"
       fi
  esac
  shift
done

if [ ! -f $DELTABTOR ]; then
  echo "could not find 'deltabtor'"
  exit 1
fi

$DELTABTOR $in $out $DDASSERT $ERRORLOG $cmd

rm -f $ERRORLOG
