#!/bin/bash

readonly DELTABTOR=./deltabtor
readonly ERRORLOG=/tmp/ddassert_error_$$.log
contribdir=$(dirname $(readlink -f $0))
readonly DDASSERT=$(readlink -f "$contribdir/ddassert")

cleanup-and-exit ()
{
  rm -f $ERRORLOG
  exit
}

die () {
  echo "*** $(basename $0): $*" 1>&2
  cleanup-and-exit
}

trap "cleanup-and-exit" SIGHUP SIGINT SIGTERM

in=""
out=""
cmd=""

while [ $# -gt 0 ]
do
  case $1 in
    -h|--help) 
               echo -n "usage: $(basename $0) "
               echo "[<option>] <infile> <outfile> <command>"
               echo
               echo "  <infile>:          the input file"
	       echo "  <outfile>:         the (reduced) output file"
               echo
               echo "  options:"
               echo "    -h,--help        print this message and exit"
               echo
               exit
               ;;
    *) if [ x"$in" = x ]; then
         in="$1"
       elif [ x"$out" = x ]; then
         out="$1"
       else
	 break
       fi
  esac
  shift
done

cmd="$*"

[ ! -f $DELTABTOR ] && die "could not find '$DELTABTOR'"
[ x"$in" = x ] && die "input file missing"
[ x"$out" = x ] && die "output file missing"
[ x"$cmd" = x ] && die "command missing"

$DELTABTOR $in $out $DDASSERT $ERRORLOG $cmd

cleanup-and-exit
