#!/bin/bash

infile=$1
outfile=$2
assertfile=/tmp/ddassert_error_$$.log
deltabtor=./deltabtor
contribdir=$(dirname $(readlink -f $0))
ddassert=$(readlink -f "$contribdir/ddassert")

if [ ! $# -eq 2 ]; then
  echo "invalid number of arguments"
  echo "usage: ddbtor <in> <out>"
  exit 1
fi

if [ ! -f $deltabtor ]; then
  echo "could not find 'deltabtor'"
  exit 1
fi

$deltabtor $infile $outfile $ddassert $assertfile

rm -f $assertfile
