#!/bin/bash

author=$1
since=$2
until=$3

if [ "$until" == "" ]; then
  until=$(date "+%Y-%m-%d")
fi

[ "$author" == "" -o "$since" == "" ] && \
  echo "error: no author and date given" && \
  echo "usage: $(basename $0) <author> <since> [<until>]" && \
  echo "      <since> date in format yyyy-mm-dd" && \
  echo "      <until> date in format yyyy-mm-dd" && \
  exit 1 

git whatchanged --author="$author" --since="$since" --until="$until" | \
  grep "^:" | \
  grep btor.*\.[cch]$ | \
  awk '{print $6}' | sort | uniq
