#!/bin/bash

cd .. 
#make clean
#indent -l10000 *.c
#./configure -cov
#make
#./test -s
#gcov *.c

counter=0
declare -a unreached

for file in *.c
do
  if [[ $file != basicbtor.c ]] && [[ $file != boolector.c ]] && \
     [[ $file != btorrand.c ]] && [[ $file != deltabtor.c ]] && \
     [[ $file != synthebtor.c ]] && [[ ${file:0:4} != test ]]; then
    if [[ ! -e $file".gcov" || ! -r $file".gcov" ]]; then
      echo "Could not read $file"".gcov file"
      exit 1
    fi

    exec 10<"btorexp.c.gcov"
    while read line <&10
    do
      if [[ ${line:0:6} = "#####:" ]]; then
        substr=${line:7}
	pos=`expr index "$substr" ":"`
	((pos--))
        unreached[$counter]=${substr:0:pos}
	((counter++))
      fi
    done

    len=$counter
    counter=1
    i=0
    lastline=""

    cat btorexp.c | while read -r line
    do
      if [[ ${unreached[$i]} = $counter ]]; then
        if [[ `expr match "$line" "{"` -ne 1 ]]; then
	  if [[ `expr match "$lastline" "if"` -eq 2 ]] || \
	     [[ `expr match "$lastline" "else"` -eq 4 ]] || \
	     [[ `expr match "$lastline" "while"` -eq 5 ]] || \
	     [[ `expr match "$lastline" "do"` -eq 2 ]] || \
	     [[ `expr match "$lastline" "for"` -eq 3 ]]; then 
	    echo -n "{ assert (0); " 
	    echo "$line }"
	  else
	    echo "assert (0);";
	    echo "$line"
	  fi
	else
	  echo "$line"
        fi	

	if [[ $i -lt $len ]]; then
	  ((i++))
	fi
      else
        echo "$line"
      fi
      ((counter++))
      lastline=$line
    done

    exit
  fi
done


