#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: ./instrumentsourcecov <source-file>"
  exit 1;
fi

counter=0
declare -a unreached
file=$1

if [[ ! -e $file".gcov" || ! -r $file".gcov" ]]; then
  echo "Could not read $file"".gcov file"
  exit 1
fi

exec 10<"$file"".gcov"
while read line <&10
do
  if [[ ${line:0:6} = "#####:" ]]; then
    substr=${line:7}
    pos=`expr index "$substr" ":"`
    ((pos--))
    unreached[$counter]=${substr:0:pos}
    ((counter++))
  fi
done

len=$counter
counter=1
i=0
lastline=""
output=$file".ins"
rm -f $output

cat $file | while read -r line
do
  if [[ ${unreached[$i]} -eq $counter ]]; then

    if [[ `expr match "$line" "{"` -ne 1 ]] \
      && [[ `expr match "$line" "else"` -ne 4 ]] \
      && [[ `expr "$line" : '.*\(:\)'` != ":" ]]; then

      if [[ `expr match "$lastline" "if"` -eq 2 ]] || \
	 [[ `expr match "$lastline" "else"` -eq 4 ]] || \
	 [[ `expr match "$lastline" "while"` -eq 5 ]] || \
	 [[ `expr match "$lastline" "do"` -eq 2 ]] || \
	 [[ `expr match "$lastline" "for"` -eq 3 ]]; then
	 echo -n "{ assert (0); " >> $output
	 echo "$line }" >> $output
      else
	echo "assert (0);" >> $output
	echo "$line" >> $output
      fi

    else
      echo "$line" >> $output
    fi	

    if [[ $i -lt $len ]]; then
      ((i++))
    fi
  else
    echo "$line" >> $output
  fi
  ((counter++))
  lastline=$line
done



