#!/bin/sh
echo "# line 1 \"../picosat/config.h\""
sed -e 's,^#include ",// #include ",' ../picosat/config.h

echo "# line 1 \"../picosat/picosat.h\""
sed -e 's,^\([a-zA-Z][a-zA-Z0-9_\* ]*\)\<picosat_,static \1picosat_,g' $h \
../picosat/picosat.h

for h in \
  btorutil.h \
  btorexit.h \
  btorlogic.h \
  btormem.h \
  btorstack.h \
  btorqueue.h \
  btorhash.h \
  btorconst.h \
  btorsat.h \
  btoraig.h \
  btoraigvec.h \
  btorexp.h \
  btorrewrite.h \
  btorparse.h \
  btorbtor.h \
  btorsmt.h \
  boolector.h \
  btorconfig.h \
  btormain.h \
  ;
do
  echo "# line 1 \"$h\""
  sed \
  -e 's,^\([a-zA-Z][a-zA-Z0-9_\* ]*\)\<btor_,static \1btor_,g' $h \
  -e 's,^#include ",// #include ",' \
  $h
done

for f in \
  ../picosat/picosat.c \
  ../picosat/version.c \
  ;
do
  echo "# line 1 \"$f\""
  sed \
  -e 's,^\([a-zA-Z][a-zA-Z0-9_\* ]*\)\<picosat_,static \1picosat_,g' $h \
  -e 's,static static,static,g' \
  -e 's,^#include ",// #include ",' \
  $f \
  | awk ' 
  /^picosat_[a-zA-Z0-9_]* *\(/{if(!static)printf ("static ")}
  {print prev;prev=$0;static=($1 == "static")}
  END{print prev}
done
  '
done

for f in \
  btormem.c \
  btorutil.c \
  btorhash.c \
  btoraig.c \
  btoraigvec.c \
  btorconst.c \
  btorexp.c \
  btorrewrite.c \
  btorsat.c \
  btorsmt.c \
  btorbtor.c \
  boolector.c \
  btormain.c \
  ;
do
  echo "# line 1 \"$f\""
  sed \
  -e 's,^\([a-zA-Z][a-zA-Z0-9_\* ]*\)\<btor_,static \1btor_,g' $h \
  -e 's,static static,static,g' \
  -e 's,^#include ",// #include ",' \
  $f \
  | awk ' 
  /^btor_[a-zA-Z0-9_]* *\(/{if(!static)printf ("static ")}
  {print prev;prev=$0;static=($1 == "static")}
  END{print prev}
  '
done
