#!/bin/sh
for h in \
  btorutil.h \
  btorexit.h \
  btorlogic.h \
  btormem.h \
  btorstack.h \
  btorqueue.h \
  btorhash.h \
  btorconst.h \
  btorsat.h \
  btoraig.h \
  btoraigvec.h \
  btorexp.h \
  btorrewrite.h \
  btorparse.h \
  btorbtor.h \
  btorsmt.h \
  boolector.h \
  btorconfig.h \
  btormain.h \
  ;
do
  #echo "# line 1 \"$h\""
  sed \
  -e 's,^\([a-zA-Z][a-zA-Z0-9_\* ]*\)\<btor_,static \1btor_,g' $h \
  -e 's,^#include ",// #include ",' \
  $h
done

for f in \
  boolector.c \
  btoraig.c \
  btoraigvec.c \
  btorbtor.c \
  btorconst.c \
  btorexp.c \
  btorhash.c \
  btormain.c \
  btormem.c \
  btorrewrite.c \
  btorsat.c \
  btorsmt.c \
  btorutil.c \
  ;
do
  #echo "# line 1 \"$f\""
  sed \
  -e 's,^\([a-zA-Z][a-zA-Z0-9_\* ]*\)\<btor_,static \1btor_,g' $h \
  -e 's,static static,static,g' \
  -e 's,^#include "b,// #include "b,' \
  $f \
  | awk ' 
  /^btor_[a-zA-Z0-9_]* *\(/{if(!static)printf ("static ")}
  {print prev;prev=$0;static=($1 == "static")}
  END{print prev}
  '
done
