#!/bin/bash

readonly filebasic="/tmp/minimizecovtestsbasic$$.tmp"
readonly fileformula="/tmp/minimizecovtestsformula$$.tmp"
readonly fileboolector="/tmp/minimizecovtestsboolector$$.tmp"
readonly covdir="covtests/"
readonly usage="./minimizecovtests [-a]"

deltabtor=unknown
for d in `echo $PATH | sed -e 's,:, ,g'` .
do
  file=$d/deltabtor
  [ -d $d ] || continue
  [ -f $file ] || continue
  deltabtor=$file
  break
done
if [[ "$deltabtor" = unknown ]]; then
  echo "*** minimizecovtests: can not find 'deltabtor'" 1>&2
  exit 1
fi

if [[ ! -e "$covdir" ]] || [[ ! -d "$covdir" ]] || [[ ! -r "$covdir" ]]; then
  echo "*** minimizecovtests: can not read coverage test directory" 1>&2
  exit 1
fi

add=0
while getopts "a" o
do
  case "$o" in
  a)	add=1;;
  [?])	echo "$usage" 1>&2; exit 1;;
  esac
done
  
./gencovformula > "$fileformula"

if [[ $? -ne 0 ]]; then
  echo "Formula could not be generated"
  exit 1
fi

rm -f "$filebasic"

if [[ "$add" -eq 1 ]]; then
  #compute test id
  maxline=`grep covtest ~/boolector/testcases | sort | tail -n 1`
  if [[ -n "$maxline" ]]; then
    maxcol=`echo "$maxline" | awk '{ print $1 }'`
    testid=${maxcol##covtest}
    ((testid++))
  else
    testid=1
  fi
fi

while read line
do
  op=`echo "$line" | awk '{ print $2 }'`
  if [[ "$op" = ulte ]]; then
    id=`echo "$line" | awk '{ print $1 }'`
    idsum=`echo "$line" | awk '{ print $4 }'`
    break
  else
    echo "$line" >> $filebasic
  fi
done < "$fileformula"

echo "found "`ls "$covdir"*.btor | wc -l`" tests"
echo "computing minimal number of tests" >&2
num=1
result=unsat
while [[ "$result" = unsat ]]
do
  echo "trying number of tests = $num" >&2
  cp $filebasic $fileformula
  echo "$id constd 32 $num" >> $fileformula
  echo "$((id + 1)) eq 1 $idsum $id" >> $fileformula
  echo "$((id + 2)) root 1 $((id + 1))" >> $fileformula
  boolector $fileformula -m 1> $fileboolector 2> /dev/null
  result=`head -n 1 $fileboolector`
  if [[ "$result" = sat ]]; then
    skipfirstline=1
    while read line
    do
      if [[ "$skipfirstline" -eq 1 ]]; then
        skipfirstline=0
      else
        if [[ `echo "$line" | awk '{ print $2 }'` -eq 1 ]]; then
	  testbase=`echo "$line" | awk '{ print $1 }'`
	  errfile="$covdir${testbase}.err"
	  csfile="$covdir${testbase}.cs"
	  reducedfile="$covdir${testbase}.red"
	  cp "$errfile" "${covdir}fileerr"
	  cp "$csfile" "${covdir}filecs"
	  echo "minimizing $testbase" >&2
	  testfile="$covdir""$testbase"".btor"
	  $deltabtor "$testfile" $reducedfile ./covdeltadebrun
	  if [[ "$add" -eq 1 ]]; then
	    cp $reducedfile ~/boolector/log/covtest$testid".btor"
	    boolector -rwl0 "$reducedfile" \
	    1> ~/boolector/log/covtest$testid".out" 2> /dev/null
	    testcasesline=covtest$testid" "`cat "$csfile"`" -o log/covtest$testid"".log log/covtest$testid"".btor"
	    echo "$testcasesline" >> ~/boolector/testcases
	    ((testid++))
          fi
	fi
      fi
    done < "$fileboolector"
  else
    ((num++))
  fi
done

if [[ "$add" -eq 1 ]]; then
  echo "added $num tests" >&2
  cd ~/boolector/log
  git add -f covtest*.*
else
  echo "minimized $num tests" >&2
fi
