#!/bin/bash

readonly fuzztestseconds=60

cd `dirname $0`
cd ..

#build picosat
cd ../picosat || exit 1
./configure -O || exit 1
make || exit 1

#build boolector
cd ../boolector
./configure -m32 -c || exit 1
make merge || exit 1

rm -f contrib/error*.*
./contrib/fuzztestboolector -v 0 &
pid=$!
sleep $fuzztestseconds 
kill $pid
if [[ `ls error*.* 2> /dev/null | wc -l` -ne 0 ]]; then
  echo ""
  echo "FUZZ TESTING FAILED"
  echo ""
  exit 1
fi

echo ""
echo "BUILD SUCCESSFUL"
echo ""
