#!/bin/sh
cd ~/boolector
make clean
./configure -r
make
rm -r -f doc
doxygen
version=`cat VERSION`
target=/tmp/boolector-$version
rm -r -f $target
mkdir $target
mkdir ${target}/bin
mkdir ${target}/lib
mkdir ${target}/include
mkdir ${target}/examples
mkdir ${target}/examples/bv
cp README $target
cp LICENSE $target
cp boolector ${target}/bin
cp libboolector.a ${target}/lib
cp boolector.h ${target}/include
cp -r doc $target
echo '#include "../../include/boolector.h"' > ${target}/examples/bv/bv.c
sed -n '2,$p' examples/bv/bv.c >> ${target}/examples/bv/bv.c
