#!/bin/bash
readonly usage='smt2aig [--no-rewriting]'

if [[ $# -ne 0 ]] && [[ $# -ne 1 ]]; then
  echo $usage
  exit 1
fi

rw=1
if [[ $# -eq 1 ]]; then
  if [[ $1 != "--no-rewriting" ]]; then 
    echo $usage
    exit 1
  fi
  rw=0
fi

boolector=`which boolector`
if [[ -z "$boolector" ]]; then
  echo "can not find 'boolector'" 1>&2
  exit 1
fi

btor2aig=`which btor2aig`
if [[ -z "$btor2aig" ]]; then
  echo "can not find 'btor2aig'" 1>&2
  exit 1
fi

if [[ $rw -eq 0 ]]; then
  $boolector -rwl 0 -db | $btor2aig --no-rewriting
else
  $boolector -rwl 0 -db | $btor2aig
fi
