#!/bin/bash
statsat=":status sat"
statunsat=":status unsat"
if [[ $# -ne 1 ]]; then
  echo "Usage: ./testsmtdir <dir>"
  exit 1;
fi
cd $1
for file in *.smt
do
  echo -n "$file"": "
  boolector $file
  ret=$?
  if [[ $ret -eq 2 ]]; then
    if [[ x"`grep "$statsat" $file`" = x ]]; then
      echo "error: $file"
      exit 1
    fi
  elif [[ $ret -eq 3 ]]; then
    if [[ x"`grep "$statunsat" $file`" = x ]]; then
      echo "error: $file"
      exit 1
    fi
  else
    echo "error: $file"
    exit 1
  fi
done
