#!/bin/bash
tmpfile="/tmp/testsmtdir$$"
statsat="status SAT"
statunsat="status UNSAT"
if [[ $# -ne 1 ]]; then
  echo "Usage: ./testsmtdir <dir>"
  exit 1;
fi
cd $1
for file in *.smt
do
  boolector $file -v -v 2> $tmpfile
  ret=$?
  if [[ $ret -eq 2 ]]; then
    if [[ x"`grep "$statsat" $tmpfile`" = x ]]; then
      echo "error: $file"
      rm -f $tmpfile
      exit 1
    fi
  elif [[ $ret -eq 3 ]]; then
    if [[ x"`grep "$statunsat" $tmpfile`" = x ]]; then
      echo "error: $file"
      rm -f $tmpfile
      exit 1
    fi
  else
    echo "error: $file"
    rm -f $tmpfile
    exit 1
  fi
done
