#!/bin/bash

readonly CONTRIBDIR=$(dirname "$(readlink -f $0)")
readonly BTORDIR=$(dirname "$CONTRIBDIR")
readonly BOOLECTOR=$BTORDIR/boolector
readonly Z3=z3

if [ $# -ne 1 ]; then
  echo "[wrapperz3] no input file given"
  exit
fi

readonly infile=$1
#tmp=/tmp/wrapperz3-$$.smt

# convert input file to smt format
#$BOOLECTOR -rwl 0 -ds $infile > $tmp

res=$($Z3 $infile | head -n1)

if [ "$res" == "sat" -o "$res" == "" ]; then
  exit 10
elif [ "$res" == "unsat" ]; then
  exit 20
else
  exit 30
fi
