language: c

cache: ccache

compiler:
  - gcc
  - clang

git:
  depth: 1
  quiet: true

os:
  - linux

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - ./contrib/setup-btor2tools.sh
  - ./contrib/setup-cadical.sh
  - ./contrib/setup-lingeling.sh
  - ./contrib/setup-picosat.sh

script:
  - $CC --version
  - |
    if [[ "$BTOR_CONFIG" == *"--python"* ]]
    then
      if [ "$TRAVIS_OS_NAME" = "linux" ]
      then
        sudo pip install -U cython
      else
        pip3 install cython
      fi
    fi
  - ./configure.sh ${BTOR_CONFIG}
  - cd build
  - make -j2
  - bin/test

env:
  - BTOR_CONFIG=''
  - BTOR_CONFIG='-g'
  - BTOR_CONFIG='--python'

matrix:
  include:
    - os: osx
      compiler: clang
      env:
        -  MATRIX_EVAL="BTOR_CONFIG='-g'"

    - os: osx
      compiler: clang

    - os: osx
      compiler: clang
      env:
        -  MATRIX_EVAL="BTOR_CONFIG='--python --py3'"

  fast_finish: true

#branches:
#  only:
#    - master
#
