#!/bin/sh

die () {
   echo "*** mkconfig.sh: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
EOF

if [ ! x"`grep '^CC=gcc$' makefile`" =  x ]
then
  patchgccversion="`gcc --version|head -1|sed -e 's/,/ /g'`"
  patchgccversion="s,gcc,$patchgccversion,g"
else
  patchgccversion="s,DUMMY,DUMMY,"
fi

sed \
  -e '/^C[A-Z]*=/!d' \
  -e 's,^,#define BTOR_,' \
  -e 's,= *, ",' \
  -e 's,$,",' \
  makefile | sed -e "$patchgccversion"

echo "#define BTOR_OS \"`uname -srmn`\""
echo "#define BTOR_COMPILED \"`date`\""

curpath=`pwd`
echo "#define BTOR_SRC_DIR   \"$curpath/\""
echo "#define BTOR_BIN_DIR   \"$curpath/bin/\""
echo "#define BTOR_BUILD_DIR \"$curpath/build/\""
echo "#define BTOR_TEST_DIR  \"$curpath/src/tests/\""
echo "#define BTOR_LOG_DIR   \"$curpath/src/tests/log/\""
echo "#define BTOR_CONTRIB_DIR \"$curpath/contrib/\""

# PUT NOTHING BELOW THE NEXT COMMENT LINE ...

#CUTHERE AND DO NOT REMOVE THIS COMMENT!

echo "#define BTOR_RELEASED \"`date`\""
echo "#define BTOR_VERSION \"`cat VERSION`\""
echo "#define BTOR_ID \"`./getgitid.sh`\""

