#!/bin/sh

die () {
   echo "*** mkconfig: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

sed \
  -e '/^C[A-Z]*=/!d' \
  -e 's,^,#define BTOR_,' \
  -e 's,=[ 	]*, ",' \
  -e 's,$,",' \
  makefile

CC="`awk '/^CC=/{print}' makefile|sed -e 's,^CC=,,'`"
case x"$CC" in
xgcc) CCVERSION="`$CC --version 2>/dev/null|head -1`";;
   *) CCVERSION="";;
esac

echo "#define BTOR_CCVERSION \"$CCVERSION\""

echo "#define BTOR_OS \"`uname -a`\""

id=""
if [ -d .git -a -f .git/HEAD ]
then
  head="`awk 'NF == 1' .git/HEAD`"
  if [ x"$head" = x ]
  then
    head="`awk '{print $2}' .git/HEAD`"
    if [ ! x"$head" = x -a -f ".git/$head" ]
    then
      id=".`cat .git/$head`"
    fi
  else
    id=".$head"
  fi
fi

echo "#define BTOR_VERSION \"`cat VERSION`$id\""

exit 0
