#!/bin/sh

die () {
  echo "*** runfuzzsmtbv: $*" 1>&2
  exit 1
}

tmp=/tmp/runfuzzsmtbv-$$.btor
trap "rm -f $tmp" 2

opts=""
cmd=""
while [ $# -gt 0 ]
do
  case $1 in
    -*|[0-9]*) opts="$opts $1";;
    *) break;;
  esac
  shift
done

cmd="$*"

[ x"$cmd" = x ] && die "command missing"

echo "options: $opts"
echo "command: $cmd"

count=0
while true
do
  rm -f $tmp
  fuzzsmtbv $opts |boolector -de > $tmp
  lines=`wc -l $tmp|awk '{print $1}'`
  echo -n "$count $lines"
  $cmd $tmp > /dev/null 2>/dev/null
  res=$?
  case $res in
    10|20)
echo -n "                                                                       \r"
    ;;
    *)
      bug=bug-${count}.btor
      cp $tmp $bug
      echo -n " $bug"
      red=red-${count}.btor
      deltabtor $bug $red $cmd
      lines=`wc -l $red|awk '{print $1}'`
      echo " $red $lines"
    ;;
  esac
  count=`expr $count + 1`
done

rm -f $tmp
