#!/bin/bash

readonly BOOLECTOR=boolector
readonly FUZZSMT=fuzzsmt
readonly DELTABTOR=deltabtor
readonly BUG_DIR=$(dirname "$(readlink -f $0)")/failed-tmp

die () {
  echo "*** $(basename $0): $*" 1>&2
  exit 1
}

val=undefined
tmp=/tmp/runfuzzsmt-$$.btor
trap "rm -f $tmp; exit" SIGHUP SIGINT SIGTERM

logic=QF_AUFBV
opts=""
cmd=""
while [ $# -gt 0 ]
do
  case $1 in
    -h|--help) 
               echo -n "usage: $(basename $0) "
               echo -en "[<option>|<fuzzsmt_option>] <command>"
               echo
               echo "  options:"
               echo "    -h,--help        print this message and exit"
	       echo -n "    --logic=<logic>  use <logic> (default: QF_AUFBV, "
	       echo "<logic>: see fuzzsmt -h)"
               echo -n "    --check=<val>    use individual return value <val> "
	       echo "for non-failure-case"
               echo
               echo "  fuzzsmt_options:   see fuzzsmt -h"
               echo
               exit
               ;;
    --logic=*) logic=$(echo "$1" | sed -e 's,^--logic=,,')
	       ;;
    --check=*) val=$(echo "$1" | sed -e 's,^--check=,,')
               ;;
    -*|[0-9]*) opts="$opts $1"
               ;;
    *) break;;
  esac
  shift
done

cmd="$*"

[ x"$cmd" = x ] && die "command missing"

echo "logic:   $logic"
echo "options: $opts"
echo "command: $cmd"

count=0
while true
do
  rm -f "$tmp"
  "$FUZZSMT" "$logic" "$opts" |"$BOOLECTOR" -de > $tmp
  buglines=`wc -l "$tmp"|awk '{print $1}'`
  echo -n "$count "
  $cmd "$tmp" > /dev/null 2>/dev/null
  res=$?

  case $res in
    10|20) echo
           ;;
    *)     if [[ x"$val" != xundefined && $res == $val ]]; then 
             echo
           else
             mkdir -p "$BUG_DIR"
             bug="$BUG_DIR"/bug-${count}.btor
             echo "; fuzzer:  $(basename $0) $opts" > "$bug"
             echo "; command: $cmd" >> "$bug"
             cat "$tmp" >> "$bug"
             echo -en "\t"
             echo -n $(basename "$bug")
             red="$BUG_DIR"/red-${count}.btor
             "$DELTABTOR" "$bug" "$red" "$cmd"
             redlines=`wc -l "$red"|awk '{print $1}'`
             echo -n " "
             echo -n $(basename "$red")
             echo -e "  ($buglines -> $redlines)"
           fi
           ;;
  esac
  count=`expr $count + 1`
done

rm -f $tmp
