#!/bin/sh
symbols=/tmp/boolector.symbols
rm -f $symbols
grep boolector_ boolector.h | \
sed -e 's, *(.*, ,' -e 's,\., ,g' | \
awk '{for (i = 1; i <= NF; i++) print $i}' | \
sed -e '/boolector_/!d' -e 's,.*\<boolector_,boolector_,' | \
sort | uniq > $symbols
num=`wc -l $symbols`
echo "keeping $num symbols"
strip="strip"
for s in btor_main `cat $symbols`; do strip="$strip -K $s"; done
lib=libboolector.a
echo -n "size of $lib before stripping " 
ls -l $lib|awk '{print $5}'
$strip $lib
echo -n "size of $lib after stripping " 
ls -l $lib|awk '{print $5}'
