#!/bin/bash
args[1]="-rwl1 -fm"
args[8]="-rwl0 -fm"
i=1
exitcode=0
for file in log/modelgen*.btor
do
  output=${file/.btor/.log}
  if [[ -z ${args[$i]} ]]; then
    cs="-m"
  else
    cs=${args[$i]}
  fi
  boolector $cs $file -o $output
  btorcheckmodel $file $output &> /dev/null
  retval=$?
  if [[ $retval -eq 1 ]]; then
    echo " invalid model: $file"
    exitcode=1
  elif [[ $retval -eq 2 ]]; then
    echo " unexpected return value: $file"
    exitcode=1
  elif [[ `cat $output | wc -l` -le 1 ]]; then
    echo " empty model: $file"
    exitcode=1
  fi
  ((i++))
done
exit $exitcode
