M quay.io/pypa/manylinux1_x86_64

RUN /opt/python/cp27-cp27m/bin/pip install cython wheel twine
RUN /opt/python/cp34-cp34m/bin/pip install cython wheel twine
RUN /opt/python/cp35-cp35m/bin/pip install cython wheel twine
RUN /opt/python/cp36-cp36m/bin/pip install cython wheel twine
RUN /opt/python/cp37-cp37m/bin/pip install cython wheel twine
RUN /opt/python/cp38-cp38/bin/pip install cython wheel twine

CMD runuser root

