#!/usr/bin/awk -f
{ 

  if ($2 == "write") {
    printf "%d write %d %d %d %d\n", $1, $3, $5, $6, $7
  } else if ($2 == "acond") {
    printf "%d cond %d %d %d %d\n", $1, $3, $5, $6, $7
  } else {
    print $0
  } 

}

