#!/bin/bash

fuzzsmt=`which fuzzsmt`
if [[ -z "$fuzzsmt" ]]; then
  echo "*** crosscheckz3: can not find 'fuzzsmt'" 1>&2
  exit 1
fi

z32008=`which z3-2008`
if [[ -z "$z32008" ]]; then
  echo "*** crosscheckz3: can not find 'z3-2008'" 1>&2
  exit 1
fi

i=0
file="/tmp/crosscheckz3$$.smt"
while true 
do 
  ((i++))
  echo -n -e "Test $i:  Boolector:\t"
  $fuzzsmt -n -a 3 -w 5 -r 20 -e 2> /dev/null 1> $file 
  boolectorresult=""
  boolectorresult=`boolector $file`
  if  [[ "$boolectorresult" != "sat" ]] && [[ "$boolectorresult" != "unsat" ]]
  then
    echo ""
    echo "ERROR"
    cp $file ./error.smt
    rm -f $file
    exit 2
  fi
  echo -n "$boolectorresult"

  z3result=""
  z3result="`boolector -rwl 0 $file -de | boolector -rwl 0 -ds | $z32008 | tr -d '\r'`"
  echo -e "\t\tZ3:\t$z3result"

  if [[ "x$z3result" = x ]]; then
    echo "Z3 CRASH"
    cp $file ./z3crash.smt
    exit 2
  fi

  if [[ "$boolectorresult" != "$z3result" ]]; then
      echo "Found different result"
      cp $file ./error.smt
      rm -f $file
      exit 1
  fi

done
