#!/bin/bash
i=0
file="/tmp/crosscheckcvc3$$.btor"
smtfile="temp.smt"
refinementlimit=100000
while true 
do 
  ((i++))
  rwl="rwl 2"
  echo -n "Test $i $rwl: "
  btorgen -n 50 2> /dev/null > $file 
  boolector -$rwl -rl $refinementlimit $file
  goldenretval=$?
  if [[ $goldenretval -ne 2 ]] && [[ $goldenretval -ne 3 ]]; then
    echo "ERROR"
    cp $file ./error.btor
    rm -f $file
    exit
  fi

  if [[ $goldenretval -eq 2 ]]; then
    status=sat
  else
    status=unsat
  fi

  for rwl in "rwl 1" "rwl 0"
  do
    echo -n "Test $i $rwl: "
    boolector -$rwl -rl $refinementlimit $file 
    retval=$?
    if [[ $retval -ne $goldenretval ]]; then
      echo "ERROR"
      cp $file ./error.btor
      rm -f $file
      exit
    fi 
  done

  boolector $file -rwl 0 -ds > $smtfile

  cvc3result="`cvc3 -lang smtlib $smtfile`"
  echo "Test $i CVC3: $cvc3result"

  if [[ "x$cvc3result" = x ]]; then
    echo "CVC3 CRASH"
    cp $file ./cvc3crash.btor
  fi

  if [[ "x$status" = xsat ]] && [[ "x$cvc3result" = xunsat ]]; then
      echo "ERROR"
      cp $file ./error.btor
      rm -f $file
      exit
  fi

  echo ""

done
