#!/bin/sh

force=no

die () {
  echo "*** mksrcrel: $*" 1>&2
  exit 1
}

intel=no

[ -f boolector.h ] || \
die "can not find 'boolector.h' (call from boolector base directory)"

while [ $# -gt 0 ]
do
  case $1 in
    -h) echo "usage: mksrcrel [-f][-h][-t]";exit 0;;
    -f) force=yes;;
    --intel) intel=yes;;
    *) die "invalid command line option '$1'";;
  esac
  shift
done

if [ ! -d doc/_build/html ]; then
  die "can not find documentation. generate documentation with 'make html' in directory ../doc/"
fi

date=`date +%y%m%d`
version=`cat VERSION`
gitid=`./getgitid|sed -e 's,^.*\.,,' -e 's,\",,' -e 's,^\(.......\).*,\1,'`

id="$version-$gitid-$date"
name=boolector-$id
dir="/tmp/$name"

if [ -d $dir ]
then
  [ $force = no ] && die "$dir already exists (use '-f')"
fi

rm -rf $dir
mkdir $dir || exit 1

cp -p \
  VERSION \
  COPYING \
  NEWS \
  README \
  configure \
  boolector.[ch] \
  boolectormain.[ch] \
  `ls btor*.[ch]|grep -v btoribv.h` \
  `ls btor*.cc |grep -v btoribv|grep -v btorimc` \
  deltabtor.c \
  synthebtor.c \
$dir/

for subdir in dumper parser
do
  mkdir $dir/$subdir/
  cp -p $subdir/*.[ch] $dir/$subdir/
done

mkdir $dir/api/
mkdir $dir/api/python
for file in boolector.pyx btorapi.pxd api_usage_examples.py README
do
  cp -p api/python/$file $dir/api/python/
done

mkdir $dir/doc
cp -pr \
  doc/_build/html/* \
$dir/doc/


if [ $intel = yes ]
then
  cp -p \
    BitVector.h \
    btoribv.h \
    btoribv.cc \
    btorimc.cc \
    testibv.cc \
    ibv.mk \
  $dir/
fi

if [ $intel = yes ]
then
cat <<EOF > $dir/README.intel
This src release contains the proprietary file

BitVector.h

which is included in 'btoribv.{h,cc}'.
EOF
fi

tar cf - \
  examples/array/* \
  examples/bv/* \
  examples/Makefile \
  examples/makefile.common | \
( cd $dir; tar xf -; )

# remove tabs from source files and replace them with whitespaces
# one tab -> 8 whitespaces
for f in `find $dir -type f -and \( -name "*.c" -o -name "*.h" -o  -name "*.cc" \)`
do
  sed -i 's/\t/        /g' $f
done

if [ $intel = yes ]
then
intelfilter=""
else
intelfilter='-e /ibv.mk/d'
fi

sed \
  -e '/test.mk/d' \
  $intelfilter \
  makefile.in > $dir/makefile.in

date=`date`
sed -e 's,@VERSION@,'"`cat VERSION`," \
    -e 's,@DATE@,'"$date," \
srcrel/README > $dir/README

sed -e '/#CUTHERE/,$d' mkconfig > $dir/mkconfig
echo 'cat<<EOF' >> $dir/mkconfig
echo "#define BTOR_RELEASED \"$date\"" >> $dir/mkconfig
echo "#define BTOR_VERSION \"`cat VERSION`\"" >> $dir/mkconfig
echo "#define BTOR_ID \"`./getgitid`\"" >> $dir/mkconfig
echo EOF >>$dir/mkconfig
chmod 755 $dir/mkconfig

cd /tmp/
rm -f $name.tar.gz
tar zcf $name.tar.gz $name
ls -l /tmp/$name.tar.gz | awk '{print $5, $NF}'
rm -rf $dir
