#!/bin/sh

force=no

die () {
  echo "*** mksrcrel: $*" 1>&2
  exit 1
}

[ -f boolector.h ] || \
die "can not find 'boolector.h' (call from boolector base directory)"

while [ $# -gt 0 ]
do
  case $1 in
    -h) echo "usage: mksrcrel [-f][-h][-t]";exit 0;;
    -f) force=yes;;
    *) die "invalid command line option '$1'";;
  esac
  shift
done

date=`date +%y%m%d`
version=`cat VERSION`
gitid=`./getgitid|sed -e 's,^.*\.,,' -e 's,\",,' -e 's,^\(.......\).*,\1,'`

id="$version-$gitid-$date"
name=boolector-$id
dir="/tmp/$name"

if [ -d $dir ]
then
  [ $force = no ] && die "$dir already exists (use '-f')"
fi

rm -rf $dir
mkdir $dir || exit 1

cp -p \
  VERSION \
  COPYING \
  NEWS \
  configure \
  boolector.[ch] \
  boolectormain.[ch] \
  btor*.[ch] \
  btor*.cc \
  deltabtor.c \
  synthebtor.c \
  Doxyfile \
$dir/

tar cf - \
  examples/array \
  examples/bv \
  examples/Makefile \
  examples/makefile.common | \
( cd $dir; tar xf -; )

sed \
  -e '/test.mk/d' \
  makefile.in > $dir/makefile.in

date=`date`
sed -e 's,@VERSION@,'"`cat VERSION`," \
    -e 's,@DATE@,'"$date," \
srcrel/README > $dir/README

sed -e '/#CUTHERE/,$d' mkconfig > $dir/mkconfig
echo 'cat<<EOF' >> $dir/mkconfig
echo "#define BTOR_RELEASED \"$date\"" >> $dir/mkconfig
echo "#define BTOR_VERSION \"`cat VERSION`\"" >> $dir/mkconfig
echo "#define BTOR_ID \"`./getgitid`\"" >> $dir/mkconfig
echo EOF >>$dir/mkconfig
chmod 755 $dir/mkconfig

cd /tmp/
rm -f $name.tar.gz
tar zcf $name.tar.gz $name
ls -l /tmp/$name.tar.gz | awk '{print $5, $NF}'
rm -rf $dir
