#!/bin/bash
#
# script arguments
#   1 ... file containing benchmarks
#   2 ... common prefix in benchmarks list
#   3 ... working director path
#   4 ... runlim options
#   5 ... solver
#   6 ... solver options
#
# disable output logging for SGE (this is handled by this script)
#$ -e /dev/null
#$ -o /dev/null

benchmark_list=$1
prefix=$2
working_dir=$3
runlim_options=$4
solver=$5
solver_optins=$6

# pick benchmark file from list of benchmarks
benchmark=`sed ${SGE_TASK_ID}'q;d' $benchmark_list`
out="$(echo ${benchmark#$prefix} | sed -e 's,/,-,g' -e 's,\.smt.*,,')"
# set stdout log file
log="$working_dir/${out}.log"
# set stderr log file
err="$working_dir/${out}.err"

echo "c launch: $*" > $log
echo "c host: `hostname`" >> $log
echo "c benchmark: $benchmark" >> $log
echo "c solver: $solver" >> $log
echo "c solver options: $solver_options" >> $log

$HOME/bin/runlim \
  $runlim_options \
  $solver \
  $solver_options \
  $benchmark >> $log 2> $err

echo "c launch: done" >> $log
