include ../makefile.common
all: array1 array2 array3
array1:
	$(CC) $(CFLAGS) $(INC) array1.c $(LIBS) -o array1
array2:
	$(CC) $(CFLAGS) $(INC) array2.c -o array2 $(LIBS)
array3:
	$(CC) $(CFLAGS) $(INC) array3.c -o array3 $(LIBS)
clean:
	rm -f array1 array2 array3
