#!/bin/sh
version=`cat ../../VERSION`
name=boolector-${version}-with-sat-solvers
tmp=/tmp/$name
log=$tmp.log
tar=${tmp}.tar.gz
rm -rf $tmp $tar $log
mkdir $tmp || exit 1
cp build.sh clean.sh makefile $tmp
mkdir $tmp/archives || exit 1
cd ../..
./srcrel/mksrcrel >> $log
boolector=`grep boolector- $log|awk '{print $NF}'`
mv $boolector $tmp/archives
for solver in picosat precosat lingeling
do
  cd ../$solver
  ./mkrelease >> $log
  archive=`grep ${solver}- $log|awk '{print $NF}'`
  mv $archive $tmp/archives
done
cd ../minisat
date=`date +%Y%m%d`
git archive --format=tar --prefix=minisat-${date}/ HEAD | \
  gzip -c > $tmp/archives/minisat-${date}.tar.gz
cd /tmp/
tar zcf $tar $name
ls -l $tar|awk '{print $5, $NF}'
rm -rf $tmp $log
