#define BTOR_FORMAT_ARITY 3
#define BTOR_FORMAT_DECLARATION 4
#define BTOR_FORMAT_OPERATOR 8
#define BTOR_FORMAT_PREDICATE 16
#define BTOR_FORMAT_CONDITIONAL 32

#define BTOR_FORMAT_TAGS         \
  BTOR_FORMAT_MACRO (invalid, 0) \
  BTOR_FORMAT_MACRO (
