#!/bin/bash
if [[ $# -ne 2 ]]; then
  echo "Usage: ./fifostack <num-bits> <power>"
  exit
fi
bw=$1
power=$2
id=1
((size = 2 ** power))
echo "$((id++)) array $bw $power"
((idarray = id - 1))
echo "$((id++)) var 1 full"
((idfull = id - 1))
echo "$((id++)) var 1 empty" 
((idempty = id - 1))
echo "$((id++)) var $bw data_out"
((iddataout = id  - 1))
echo "$((id++)) var $power head"
((idhead = id - 1))
echo "$((id++)) var $power tail"
((idtail = id - 1))
((idzero = id))
((idone = id + 1))
for ((i = 0; i < size; i++))
do
  echo "$((id++)) constd $power $i"
done
((idmaxconst = id - 1))
echo ""
if [[ $power -gt 1 ]]; then
  echo "$((id++)) zero 1"
  ((idzero1 = id - 1))
  echo "$((id++)) one 1"
  ((idone1 = id - 1))
  echo ""
else
  idzero1=$idzero
  idone1=$idone
fi
echo "$((id++)) var 1 enqeue"
((idenqueue = id - 1))
echo "$((id++)) var 1 deqeue"
((iddequeue = id - 1))
echo "$((id++)) var 1 reset"
((idreset = id - 1))
echo "$((id++)) var $bw data_in"
((iddatain = id - 1))
echo "$((id++)) xor 1 $idenqueue $iddequeue"
((idxor = id - 1))
echo ""

echo ";next of head"
echo "$((id++)) next $power $idhead $idzero" 

echo ""
echo ";next of tail"
echo "$((id++)) sub $power $idtail $idone"
((idtailsub = id - 1))
echo "$((id++)) and 1 -$idfull -$idempty"
((lastid = id - 1))
echo "$((id++)) cond $power $lastid $idtailsub $idtail"
((idtailcond = id - 1))
echo "$((id++)) add $power $idtail $idone" 
((idtailadd = id - 1))
echo "$((id++)) cond $power $idfull $idtail $idtailadd"
((lastid = id - 1))
echo "$((id++)) cond $power $idenqueue $lastid $idtailcond"
((lastid = id - 1))
echo "$((id++)) cond $power $idxor $lastid $idtail"
((lastid = id - 1))
echo "$((id++)) cond $power $idreset $lastid $idzero"
((lastid = id - 1))
echo "$((id++)) next $power $idtail $lastid"

echo ""
echo ";next of full"
echo "$((id++)) eq 1 $idtail $idmaxconst"
((lastid = id - 1))
echo "$((id++)) cond 1 $lastid $idone1 $idfull"
((lastid = id - 1))
echo "$((id++)) cond 1 $iddequeue $idzero1 $lastid"
((lastid = id - 1))
echo "$((id++)) cond 1 $idxor $lastid $idfull"
((lastid = id - 1))
echo "$((id++)) cond 1 $idreset $lastid $idzero1"
((lastid = id - 1))
echo "$((id++)) next 1 $idfull $lastid"

echo ""
echo ";next of empty"
echo "$((id++)) eq 1 $idtail $idone"
((lastid = id - 1))
echo "$((id++)) cond 1 $lastid $idone1 $idempty"
((lastid = id - 1))
echo "$((id++)) cond 1 $idenqueue $idzero1 $lastid"
((lastid = id - 1))
echo "$((id++)) cond 1 $idxor $lastid $idempty"
((lastid = id - 1))
echo "$((id++)) cond 1 $idreset $lastid $idone1"
((lastid = id - 1))
echo "$((id++)) next 1 $idempty $lastid"

echo ""
echo ";next of data_out"
echo "$((id++)) read $bw $idarray $idtailsub"
((lastid = id - 1))
echo "$((id++)) cond $bw $idempty $iddataout $lastid"
((lastid = id - 1))
echo "$((id++)) next $bw $iddataout $lastid"

echo ""
echo ";next of memory"
echo "$((id++)) write $bw $idarray $idtail $iddatain"
((lastid = id - 1))
echo "$((id++)) cond $bw $idfull $idarray $lastid"
((idarraycond = id - 1))
